//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckPrimeNumber", ReplyAction="http://tempuri.org/IService1/CheckPrimeNumberResponse")]
        string CheckPrimeNumber(int primeNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckPrimeNumber", ReplyAction="http://tempuri.org/IService1/CheckPrimeNumberResponse")]
        System.Threading.Tasks.Task<string> CheckPrimeNumberAsync(int primeNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SumOfDigits", ReplyAction="http://tempuri.org/IService1/SumOfDigitsResponse")]
        int SumOfDigits(int digits);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SumOfDigits", ReplyAction="http://tempuri.org/IService1/SumOfDigitsResponse")]
        System.Threading.Tasks.Task<int> SumOfDigitsAsync(int digits);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReverseString", ReplyAction="http://tempuri.org/IService1/ReverseStringResponse")]
        string ReverseString(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReverseString", ReplyAction="http://tempuri.org/IService1/ReverseStringResponse")]
        System.Threading.Tasks.Task<string> ReverseStringAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintTag", ReplyAction="http://tempuri.org/IService1/PrintTagResponse")]
        string PrintTag(string tag, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintTag", ReplyAction="http://tempuri.org/IService1/PrintTagResponse")]
        System.Threading.Tasks.Task<string> PrintTagAsync(string tag, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SortNumbers", ReplyAction="http://tempuri.org/IService1/SortNumbersResponse")]
        int[] SortNumbers(string sortType, int[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SortNumbers", ReplyAction="http://tempuri.org/IService1/SortNumbersResponse")]
        System.Threading.Tasks.Task<int[]> SortNumbersAsync(string sortType, int[] data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AssignmentClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AssignmentClient.ServiceReference1.IService1>, AssignmentClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckPrimeNumber(int primeNumber) {
            return base.Channel.CheckPrimeNumber(primeNumber);
        }
        
        public System.Threading.Tasks.Task<string> CheckPrimeNumberAsync(int primeNumber) {
            return base.Channel.CheckPrimeNumberAsync(primeNumber);
        }
        
        public int SumOfDigits(int digits) {
            return base.Channel.SumOfDigits(digits);
        }
        
        public System.Threading.Tasks.Task<int> SumOfDigitsAsync(int digits) {
            return base.Channel.SumOfDigitsAsync(digits);
        }
        
        public string ReverseString(string value) {
            return base.Channel.ReverseString(value);
        }
        
        public System.Threading.Tasks.Task<string> ReverseStringAsync(string value) {
            return base.Channel.ReverseStringAsync(value);
        }
        
        public string PrintTag(string tag, string data) {
            return base.Channel.PrintTag(tag, data);
        }
        
        public System.Threading.Tasks.Task<string> PrintTagAsync(string tag, string data) {
            return base.Channel.PrintTagAsync(tag, data);
        }
        
        public int[] SortNumbers(string sortType, int[] data) {
            return base.Channel.SortNumbers(sortType, data);
        }
        
        public System.Threading.Tasks.Task<int[]> SortNumbersAsync(string sortType, int[] data) {
            return base.Channel.SortNumbersAsync(sortType, data);
        }
    }
}
